version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ../api/redis_data:/data
    ports:
      - "6379:6379"
