version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ../api/redis_data:/data
    ports:
      - "6379:6379"
    networks:
        - todo-type-app
  elasticsearch:
    image: elasticsearch:latest
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
        - ../api/elasticsearch_data:/usr/share/elasticsearch/data
    ports:
        - "9200:9200"
    networks:
        - todo-type-app
  kibana:
    image: kibana:latest
    ports:
        - "5601:5601"
    networks:
        - todo-type-app
    depends_on:
        - elasticsearch