version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ../api/redis_data:/data
    ports:
      - "6379:6379"
    networks:
        - todo-type-app
  elasticsearch:
    image: elasticsearch:7.17.10
    volumes:
        - ../api/elasticsearch_data:/data
        - ./yml/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
        - "9200:9200"
    networks:
        - todo-type-app
  kibana:
    image: kibana:7.17.10
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
        - "5601:5601"
    networks:
        - todo-type-app
    volumes:
      - ./yml/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
        - elasticsearch
networks:
  todo-type-app: